# Generated by Django 2.0.5 on 2018-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='static/uploads/')),
                ('tipo', models.CharField(choices=[('casca', 'casca'), ('cera', 'cera'), ('flor', 'flor'), ('folha', 'folha'), ('fruta', 'fruta'), ('raiz', 'raiz'), ('seiva', 'seiva')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('conteudo', models.TextField()),
                ('plantas_base', models.ManyToManyField(to='plyntas.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
                ('chave', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='sintomas',
            field=models.ManyToManyField(related_name='receitas', to='plyntas.Sintoma'),
        ),
    ]
