# Generated by Django 2.0.5 on 2018-06-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plyntas', '0002_auto_20180626_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintoma',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sintomas', to='plyntas.Categoria'),
        ),
    ]
